name: overscripted
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.6
    - jupyter=1.0.0
    - pyarrow=0.9.0
    - pandas=0.23.0
    - dask=0.17.5
    - findspark=1.2.0
    - tldextract=2.2.0
